### ISSUE TITLE
Bugfix: MongoDB database not accessible via Mongo Compass

### ISSUE THREAD

**Issue by Kyle-HeatEng** [Kyle-HeatEng/asite#1]
## Steps to reproduces
- Spin up the `docker-compose.yaml`
- Can't connect from MongoDB compass via `mongodb://localhost:27017`

This was due to the packages needing to connect to the database via the package name `mongodb://mongodb:27017`. The order services requires readding from both `events` and `transaction` collections and hence a transaction is required to prevent race conditions. This required the local database to have a replica database created in this section of the `docker-compose.yaml`.
```yaml
 mongo-init:
    image: mongo:8
    container_name: mongo-init
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongosh --host mongodb:27017 --eval
      '
      rs.initiate( {
         _id : "rs0",
         members: [
         { _id: 0, host: "mongodb:27017" }
        ]
      })
      '
    networks:
      - app-network
```
However, `MongoDB` only allows for for host to be `localhost` or via domain name. The choice was to priorities the services working over developer UX. 

In production situation we will most likely not be self hosting our database so this issue could be solved via migrating to Atlas https://www.mongodb.com/products/platform/atlas-database
